#!/usr/bin/python3

import argparse
import subprocess


def sh(cmd):
    out = subprocess.call(cmd, shell=True)
    if out:
        exit(out)

parser = argparse.ArgumentParser("""
Helper for running our MBTAI project.
""")
parser.add_argument('-b', '--build', action='store_true')
parser.add_argument('targets', nargs='*', default=['ci'])
args = parser.parse_args()

if args.build:
    sh("docker build --rm -t mbtai .")

run_interactive = 'docker run --rm -it -v `pwd`:/code -w /code mbtai '
targets = set(args.targets)

if set(['test', 'check', 'ci']) & targets:
    sh(run_interactive + 'nosetests mbtai --nocapture')

if set(['flake', 'check', 'ci']) & targets:
    sh(run_interactive + 'flake8 mbtai')

if set(['doc', 'ci']) & targets:
    sh(run_interactive + 'env PYTHONPATH=. pdoc mbtai --overwrite --html --html-dir docs')

if 'repl' in targets:
    sh(run_interactive + 'python')
